# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='hello', max_length=10000),
            preserve_default=False,
        ),
    ]
